import { computed, onMounted } from "vue"
import { useI18n } from "vue-i18n"
import { useUserStore } from "@/shared/stores/user"
import { AVAILABLE_SCOPE_IDS, WRITE_SCOPE_IDS } from "@/modules/admin-oauth-clients/lib/form"
import {
  AVAILABLE_GRANT_TYPES,
  GRANT_TYPE_AUTHORIZATION_CODE,
  GRANT_TYPE_DEVICE_CODE,
  GRANT_TYPE_REFRESH_TOKEN,
  type ManagedGrantType,
} from "@/modules/admin-oauth-clients/lib/grant-types"
import { useOAuthClientForms } from "@/modules/admin-oauth-clients/composables/useOAuthClientForms"
import { useOAuthClientList } from "@/modules/admin-oauth-clients/composables/useOAuthClientList"
import { useOAuthClientRowActions } from "@/modules/admin-oauth-clients/composables/useOAuthClientRowActions"
import { useOAuthClientSecretDialog } from "@/modules/admin-oauth-clients/composables/useOAuthClientSecretDialog"
import { useOAuthClientStats } from "@/modules/admin-oauth-clients/composables/useOAuthClientStats"
import { useOAuthClientWebhooks } from "@/modules/admin-oauth-clients/composables/useOAuthClientWebhooks"

const SCOPE_LABEL_KEY: Record<(typeof AVAILABLE_SCOPE_IDS)[number], string> = {
  "user:read": "adminOAuthClients.scope.userRead",
  "bindings:read": "adminOAuthClients.scope.bindingsRead",
  "game-data:read": "adminOAuthClients.scope.gameDataRead",
  "game-data:write": "adminOAuthClients.scope.gameDataWrite",
  "station:room:write": "adminOAuthClients.scope.stationRoomWrite",
  "openid": "adminOAuthClients.scope.openid",
  "profile": "adminOAuthClients.scope.profile",
  "email": "adminOAuthClients.scope.email",
  "offline_access": "adminOAuthClients.scope.offlineAccess",
}

const GRANT_TYPE_LABEL_KEY: Record<ManagedGrantType, string> = {
  [GRANT_TYPE_AUTHORIZATION_CODE]: "adminOAuthClients.form.grantType.authorizationCode",
  [GRANT_TYPE_DEVICE_CODE]: "adminOAuthClients.form.grantType.deviceCode",
  [GRANT_TYPE_REFRESH_TOKEN]: "adminOAuthClients.form.grantType.refreshToken",
}

export function useOAuthClientManagement() {
  const userStore = useUserStore()
  const { t } = useI18n()
  const AVAILABLE_SCOPES = computed(() =>
    AVAILABLE_SCOPE_IDS.map((id) => ({
      id,
      label: t(SCOPE_LABEL_KEY[id]),
      write: WRITE_SCOPE_IDS.has(id),
    }))
  )
  const AVAILABLE_GRANT_TYPE_OPTIONS = computed(() =>
    AVAILABLE_GRANT_TYPES.map((id) => ({
      id,
      label: t(GRANT_TYPE_LABEL_KEY[id]),
    }))
  )

  const { loading, clients, loadClients } = useOAuthClientList()
  async function refreshClientsStrict() {
    await loadClients({ throwOnError: true, notifyOnError: false })
  }
  const { secretDisplayOpen, displayedSecret, showSecret, copySecret } = useOAuthClientSecretDialog()
  const {
    actionLoading,
    deleteConfirmOpen,
    clientToDelete,
    rotateConfirmOpen,
    clientToRotate,
    revokeConfirmOpen,
    clientToRevoke,
    confirmDelete,
    executeDelete,
    toggleActive,
    confirmRotateSecret,
    handleRotateSecret,
    handleRestore,
    confirmRevoke,
    handleRevoke,
  } = useOAuthClientRowActions({
    loadClients: refreshClientsStrict,
    onSecretGenerated: showSecret,
  })
  const {
    createOpen,
    newClientId,
    newName,
    newClientType,
    newScopes,
    newRedirectUris,
    newPostLogoutRedirectUris,
    newGrantTypes,
    newDevicePolicy,
    creating,
    editOpen,
    editClientId,
    editName,
    editClientType,
    editScopes,
    editRedirectUris,
    editPostLogoutRedirectUris,
    editGrantTypes,
    editDevicePolicy,
    saving,
    toggleNewScope,
    toggleEditScope,
    toggleNewGrantType,
    toggleEditGrantType,
    updateNewDevicePolicy,
    updateEditDevicePolicy,
    setCreateOpen,
    setEditOpen,
    updateNewClientId,
    updateNewName,
    updateEditName,
    updateNewClientType,
    updateEditClientType,
    updateNewRedirectUri,
    addNewRedirectUri,
    removeNewRedirectUri,
    updateEditRedirectUri,
    addEditRedirectUri,
    removeEditRedirectUri,
    updateNewPostLogoutRedirectUri,
    addNewPostLogoutRedirectUri,
    removeNewPostLogoutRedirectUri,
    updateEditPostLogoutRedirectUri,
    addEditPostLogoutRedirectUri,
    removeEditPostLogoutRedirectUri,
    handleCreate,
    openEdit,
    handleSaveEdit,
  } = useOAuthClientForms({
    loadClients: refreshClientsStrict,
    onSecretGenerated: showSecret,
  })
  const {
    statsOpen,
    statsLoading,
    statsClientId,
    stats,
    statsFrom,
    statsTo,
    statsBucket,
    showStats,
    applyStatsFilters,
    resetStatsFilters,
  } = useOAuthClientStats()
  const {
    webhookOpen,
    webhookClientId,
    webhooks,
    webhookLoading,
    webhookSaving,
    webhookDeleting,
    editingWebhook,
    webhookFormOpen,
    callbackUrl,
    bearer,
    enabled,
    clearBearer,
    webhookDeleteConfirmOpen,
    webhookToDelete,
    loadWebhooks,
    openWebhookManager,
    openCreateWebhook,
    openEditWebhook,
    saveWebhook,
    confirmDeleteWebhook,
    deleteWebhook,
  } = useOAuthClientWebhooks()

  onMounted(() => {
    void loadClients()
  })

  return {
    userStore,
    loading,
    clients,
    actionLoading,
    createOpen,
    newClientId,
    newName,
    newClientType,
    newScopes,
    newRedirectUris,
    newPostLogoutRedirectUris,
    newGrantTypes,
    newDevicePolicy,
    creating,
    editOpen,
    editClientId,
    editName,
    editClientType,
    editScopes,
    editRedirectUris,
    editPostLogoutRedirectUris,
    editGrantTypes,
    editDevicePolicy,
    saving,
    statsOpen,
    statsLoading,
    statsClientId,
    stats,
    statsFrom,
    statsTo,
    statsBucket,
    secretDisplayOpen,
    displayedSecret,
    deleteConfirmOpen,
    clientToDelete,
    rotateConfirmOpen,
    clientToRotate,
    revokeConfirmOpen,
    clientToRevoke,
    webhookOpen,
    webhookClientId,
    webhooks,
    webhookLoading,
    webhookSaving,
    webhookDeleting,
    editingWebhook,
    webhookFormOpen,
    callbackUrl,
    bearer,
    enabled,
    clearBearer,
    webhookDeleteConfirmOpen,
    webhookToDelete,
    AVAILABLE_SCOPES,
    AVAILABLE_GRANT_TYPE_OPTIONS,
    confirmDelete,
    executeDelete,
    toggleNewScope,
    toggleEditScope,
    toggleNewGrantType,
    toggleEditGrantType,
    updateNewDevicePolicy,
    updateEditDevicePolicy,
    setCreateOpen,
    setEditOpen,
    updateNewClientId,
    updateNewName,
    updateEditName,
    updateNewClientType,
    updateEditClientType,
    updateNewRedirectUri,
    addNewRedirectUri,
    removeNewRedirectUri,
    updateEditRedirectUri,
    addEditRedirectUri,
    removeEditRedirectUri,
    updateNewPostLogoutRedirectUri,
    addNewPostLogoutRedirectUri,
    removeNewPostLogoutRedirectUri,
    updateEditPostLogoutRedirectUri,
    addEditPostLogoutRedirectUri,
    removeEditPostLogoutRedirectUri,
    handleCreate,
    openEdit,
    handleSaveEdit,
    toggleActive,
    confirmRotateSecret,
    handleRotateSecret,
    handleRestore,
    confirmRevoke,
    handleRevoke,
    showStats,
    applyStatsFilters,
    resetStatsFilters,
    loadWebhooks,
    openWebhookManager,
    openCreateWebhook,
    openEditWebhook,
    saveWebhook,
    confirmDeleteWebhook,
    deleteWebhook,
    copySecret,
    loadClients,
  }
}
