import { describe, expect, it } from "bun:test"
import {
  buildMusicScoreAssetPath,
  collectBpmRange,
  formatBpmValue,
  parseChartBpm,
  resolveMusicScoreUrl,
} from "./music-bpm"

const SIMPLE_CHART = `This file was generated by Ched 2.6.2.0.
#TITLE "Tell your world"

#00002: 4

#BPM01: 150
#00008: 01

#00016:0000120000120000
#02718: 0012000000000000
`

const MULTI_BPM_CHART = `#BPM01: 120
#BPM02: 240
#00008: 01
#00408: 02
#00808: 01
#01008: 00
#01500: 4
`

describe("parseChartBpm", () => {
  it("parses the palette and events of a single-BPM chart", () => {
    const info = parseChartBpm(SIMPLE_CHART)

    expect(info).not.toBeNull()
    expect(info?.mainBpm).toBe(150)
    expect(info?.events).toHaveLength(1)
    expect(info?.events[0]).toMatchObject({ bar: 0, bpm: 150 })
    // Highest seen bar is 027 → 28 bars.
    expect(info?.barCount).toBe(28)
    expect(info?.duration).toBeCloseTo((28 / 150) * 4 * 60, 5)
  })

  it("collapses duplicate events and picks the longest-running BPM as main", () => {
    const info = parseChartBpm(MULTI_BPM_CHART)

    expect(info).not.toBeNull()
    // 120 for bars 0-4 and 8-16, 240 for bars 4-8.
    expect(info?.events.map((event) => event.bpm)).toEqual([120, 240, 120])
    expect(info?.mainBpm).toBe(120)
    expect(collectBpmRange(info!)).toEqual([120, 240])
  })

  it("returns null when the chart has no BPM data", () => {
    expect(parseChartBpm("#TITLE \"empty\"\n#00002: 4")).toBeNull()
    expect(parseChartBpm("")).toBeNull()
  })
})

describe("music score asset paths", () => {
  it("builds the padded chart path", () => {
    expect(buildMusicScoreAssetPath(1, "expert")).toBe("startapp/music/music_score/0001_01/expert.txt")
    expect(buildMusicScoreAssetPath(226, "MASTER")).toBe("startapp/music/music_score/0226_01/master.txt")
    expect(buildMusicScoreAssetPath(0, "expert")).toBeNull()
    expect(buildMusicScoreAssetPath(1, " ")).toBeNull()
  })

  it("resolves a full URL for the region", () => {
    expect(resolveMusicScoreUrl("jp", 1, "expert")).toContain("/jp-assets/startapp/music/music_score/0001_01/expert.txt")
  })
})

describe("formatBpmValue", () => {
  it("trims float noise", () => {
    expect(formatBpmValue(150)).toBe("150")
    expect(formatBpmValue(92.5)).toBe("92.5")
    expect(formatBpmValue(127.999999)).toBe("128")
    expect(formatBpmValue(Number.NaN)).toBe("-")
  })
})
